---
- name: Get attribute 
  hosts: localhost
  connection: local
  vars:
  - object: root

  gather_facts: False
  roles:
  - manageiq-core.manageiq-automate
  - manageiq-core.manageiq-vmdb

  tasks:
    - name: "Get var1 from root"
      manageiq_automate:
        workspace: "{{ workspace }}"
        get_attribute:

          object: "root"
          attribute: "var1"
      register:    result

    - debug: msg="attribute result dictionary {{ result }}"
    - debug: msg="attribute result value is {{ result.value }}"

