---
- name: Get Decrypted root attribute
  hosts: localhost
  connection: local
  vars:
  - object: root

  gather_facts: False
  roles:
  - manageiq-core.manageiq-automate

  tasks:
   - name: "Decrypt attribute fred from root object"
      manageiq_automate:
        workspace: "{{ workspace }}"
        get_decrypted_attribute:
          object: root
          attribute: fred
      register: attribute

      ignore_errors: yes

   - debug: msg="get decrypted root attribute:{{ attribute }}"
