---
- name: Set retry interval
  hosts: localhost
  connection: local
  vars:
  - object: root
  - interval: 600

  gather_facts: False
  roles:
  - manageiq-core.manageiq-automate

  tasks:

    - name: Set Retry
      manageiq_automate:
        workspace: "{{ workspace }}"
        set_retry:
          interval: "{{ interval }}"
