---
- name: Set root attributes unsigned
  hosts: localhost
  connection: local
  vars:
  - object: root
  - manageiq_validate_certs: False

  gather_facts: False
  roles:
  - manageiq-core.manageiq-automate

  tasks:
    - name: "Set root attributes"
      manageiq_automate:
        workspace: "{{ workspace }}"
        set_attributes:
          object: "root"
          attributes:
            family_name: "timmer"
            eldest_son: "reed"
            youngest_son: "olaf"
      register: attributes

    - debug: msg="set root attributes unsigned:{{ attributes }}"
