---
- name: Set root attribute
  hosts: localhost
  connection: local
  vars:
  - object: root

  gather_facts: False
  roles:
  - manageiq-core.manageiq-automate

  tasks:
    - name: "Set my_name var in root"
      manageiq_automate:
        workspace: "{{ workspace }}"
        set_attribute:
          object: "root"
          attribute: "my_name"
          value:  "unchanged"
      register: attribute

    - debug: msg="set root attribute:{{ attribute }}"
