---
- name: Set retry interval with input
  hosts: localhost
  connection: local
  vars:
  - object: root

  gather_facts: False
  roles:
  - manageiq-core.manageiq-automate

  tasks:

    - name: Set Retry
      manageiq_automate:
        workspace: "{{ workspace }}"
        set_retry:
          interval: "{{ miq_retry_interval |default(60,true) }}"
      register:    result

    - debug: msg="Retry interval set to {{ miq_retry_interval }}"
